routes/admin.php
<?php
Route::get('admin/login','Auth\AuthController@getLogin')->name('login');
Route::post('admin/login','Auth\AuthController@postLogin')->name('admins.login');
Route::get('admin/logout','Auth\AuthController@logout')->name('logout');
Route::get('/support/{id}', 'Admins\SupportsController@view')->name('support.support.view'); 
// Admin route 
Route::group(['prefix' => 'admin','middleware' =>'auth'], function () {
    Route::get('/', 'Admins\DashboardController@index')
         ->name('admins.dashboard.index');
    Route::group([  
    'prefix' => 'category_course',
    'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'CourseCategoryController@index')->name('category_course.index')->middleware('permission:view_category_course');
        Route::get('/create', 'CourseCategoryController@create')->name('category_course.create')->middleware('permission:create_category_course');
        Route::post('/store', 'CourseCategoryController@store')->name('category_course.store');
        Route::get('/edit/{id}', 'CourseCategoryController@edit')->name('category_course.edit')->middleware('permission:edit_category_course');
        Route::post('/update/{id}', 'CourseCategoryController@update')->name('category_course.update');
        Route::delete('/delete/{id}', 'CourseCategoryController@destroy')->name('category_course.destroy')->middleware('permission:delete_category_course');
    }); 
    Route::group([  
        'prefix' => 'course',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'CourseController@index')->name('course.index')->middleware('permission:view_course');
        Route::get('/create', 'CourseController@create')->name('course.create')->middleware('permission:create_course');
        Route::post('/store', 'CourseController@store')->name('course.store');
        Route::get('/edit/{id}', 'CourseController@edit')->name('course.edit')->middleware('permission:edit_course');
        Route::post('/update/{id}', 'CourseController@update')->name('course.update');
        Route::get('/delete/{id}', 'CourseController@destroy')->name('course.destroy')->middleware('permission:delete_course');
    });
    Route::group([  
        'prefix' => 'position',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'PositionController@index')->name('position.position.index');
    }); 
    Route::group([  
        'prefix' => 'question',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/{id?}', 'QuestionController@index')->name('question.question.index');
        Route::get('/create/question/{id?}', 'QuestionController@create')->name('question.question.create');
        Route::post('/store', 'QuestionController@store')->name('question.question.store');
        Route::get('/edit/{id}', 'QuestionController@edit')->name('question.question.edit');
        Route::post('/update/{id}', 'QuestionController@update')->name('question.question.update');
        Route::delete('/delete/{id}', 'QuestionController@destroy')->name('question.question.destroy');
    }); 
    Route::group([  
        'prefix' => 'answer',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/{id}', 'AnswerController@index')->name('answer.answer.index');
        Route::get('/create/{id}', 'AnswerController@create')->name('answer.answer.create');
        Route::post('/store/{id}', 'AnswerController@store')->name('answer.answer.store');
        Route::get('/edit/{id}', 'AnswerController@edit')->name('answer.answer.edit');
        Route::post('/update/{id}', 'AnswerController@update')->name('answer.answer.update');
        Route::delete('/delete/{id}', 'AnswerController@destroy')->name('answer.answer.destroy');
    });    
    Route::group([  
        'prefix' => 'point',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'PointController@index')->name('point.point.index');

    }); 
    Route::group([  
        'prefix' => 'permission',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'PermisionController@index')->name('permission.permission.index')->middleware('permission:view_permission');
        Route::get('/detail/{id}', 'PermisionController@show')->name('permission.permission.show')->middleware('permission:edit_permission');
        Route::post('/update/{id}', 'PermisionController@update')->name('permission.permission.update');
    });    
    Route::group([  
        'prefix' => 'chat',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/{id?}', 'ChatController@index')->name('chat.chat.index');
        Route::post('/create', 'ChatController@store')->name('chat.chat.store');
        Route::post('/upload', 'ChatController@upload');
        Route::get('/conversion/delete/{id}', 'ChatController@deleteConversion')->name('chat.chat.delete_conversion');
        Route::get('/message/delete/{id}', 'ChatController@deleteMessage')->name('chat.chat.delete_message');
    });
    Route::group([  
        'prefix' => 'tracking',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'TrackingController@index')->name('tracking.tracking.index');
    });
    Route::get('/school/search-class/{id}', 'Admins\ClassController@classSchool');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'namespace' => 'Admins',
    'middleware' =>'auth'
], function () {
    Route::get('/', 'HomeController@index')->name('home.index');
});
Route::group(['prefix' => 'admin','middleware' =>'auth'], function () {

    Route::group([
        'prefix' => 'school',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'SchoolController@index')->name('school_index')->middleware('permission:view_school');
        Route::get('/create', 'SchoolController@create')->name('school_create')->middleware('permission:create_school');
        Route::post('/create', 'SchoolController@store');
        Route::get('/delete/{id}', 'SchoolController@delete')->name('school_delete')->middleware('permission:delete_school');
        Route::get('/edit/{id}', 'SchoolController@edit')->name('school_edit')->middleware('permission:edit_school');
        Route::post('/update/{id}', 'SchoolController@update')->name('school_update');
        Route::get('/class/{id}', 'ClassController@listClass')->name('list_class');
        Route::get('class/create/{id}', 'SchoolController@createClass')->name('school_create.class')->middleware('permission:create_class');
        Route::post('class/create', 'SchoolController@storeClass')->name('school_store.class');
        Route::get('class/edit/{id}', 'SchoolController@editClass')->name('school_edit.class');
        Route::post('class/update/{id}', 'SchoolController@updateClass')->name('school_update.class');
    });
    Route::group([
        'prefix' => 'class',
        'namespace' => 'Admins',
    ], function () {
        Route::get('/', 'ClassController@index')->name('class_index')->middleware('permission:view_class');
        Route::get('/create', 'ClassController@create')->name('class_create')->middleware('permission:create_class');
        Route::post('/create', 'ClassController@store');
        Route::get('/delete/{id}', 'ClassController@delete')->name('class_delete')->middleware('permission:delete_class');
        Route::get('/edit/{id}', 'ClassController@edit')->name('class_edit')->middleware('permission:edit_class');
        Route::post('/update/{id}', 'ClassController@update')->name('class_update');
        Route::get('/students/{id}/{school_id?}', 'ClassController@listStudent')->name('list_student');
        Route::get('/student/create/{id}', 'ClassController@createStudent')->name('class_create.student');
        Route::post('/student/create', 'ClassController@storeStudent')->name('class_store.student');
        Route::get('/student/edit/{id}', 'ClassController@editStudent')->name('class_edit.student');
        Route::post('/student/update/{id}', 'ClassController@updateStudent')->name('class_update.student');
    });
    Route::group([
        'prefix' => 'student',
        'namespace' => 'Admins',
    ], function () {
        // student
        Route::get('/', 'StudentController@index')->name('student.index')->middleware('permission:view_student');
        Route::get('/create', 'StudentController@create')->name('student.create')->middleware('permission:create_student');
        Route::post('student-store', 'StudentController@store')->name('student.store');
        Route::get('/edit/{id}', 'StudentController@edit')->name('student.edit')->middleware('permission:edit_student');
        Route::post('/update/{id}', 'StudentController@update')->name('student.update');
        Route::get('/destroy/{id}', 'StudentController@destroy')->name('student.destroy')->middleware('permission:delete_student');
        //ajax
        Route::get('/search-class', 'StudentController@searchClassAjax');
        Route::get('/update-status', 'StudentController@updateStatusAjax');
    });
    Route::group([
        'prefix' => 'teacher',
        'namespace' => 'Admins',
    ], function () {

        //teacher
        Route::get('/', 'TeacherController@index')->name('teacher.index')->middleware('permission:view_teacher');
        Route::get('/create', 'TeacherController@create')->name('teacher.create')->middleware('permission:create_teacher');
        Route::post('/store', 'TeacherController@store')->name('teacher.store');
        Route::get('/edit/{id}', 'TeacherController@edit')->name('teacher.edit')->middleware('permission:edit_teacher');
        Route::post('/update/{id}', 'TeacherController@update')->name('teacher.update');
        Route::get('/destroy/{id}', 'TeacherController@destroy')->name('teacher.destroy')->middleware('permission:delete_teacher');
        Route::get('/list-teacher/{id}', 'TeacherController@listTeacher');


    });
    Route::group([
        'prefix' => 'map',
        'namespace' => 'Admins',
    ], function () {
        Route::get('', 'MapController@index')->name('map_index')->middleware('permission:view_map');
        Route::get('/create', 'MapController@create')->name('map_create')->middleware('permission:create_map');
        Route::post('/create', 'MapController@store');
        Route::get('/delete/{id}', 'MapController@delete')->name('map_delete')->middleware('permission:delete_map');
        Route::get('/edit/{id}', 'MapController@edit')->name('map_edit')->middleware('permission:edit_map');
        Route::post('/update/{id}', 'MapController@update')->name('map_update');
    });
    Route::group([
        'prefix' => 'refer',
        'namespace' => 'Admins',
    ], function () {

        //refer
        Route::get('/', 'ReferController@index')->name('refer.index');
        Route::get('/create', 'ReferController@create')->name('refer.create');
        Route::post('/store', 'ReferController@store')->name('refer.store');
        Route::get('/edit/{id}', 'ReferController@edit')->name('refer.edit');
        Route::post('/update/{id}', 'ReferController@update')->name('refer.update');
        Route::get('/destroy/{id}', 'ReferController@destroy')->name('refer.destroy');
    });
    Route::group([
        'prefix' => 'grades',
        'namespace' => 'Admins',
    ], function () {
        Route::get('', 'GradeController@index')->name('grade_index')->middleware('permission:view_grade');
        Route::get('/create', 'GradeController@create')->name('grade_create')->middleware('permission:create_grade');
        Route::post('/create', 'GradeController@store');
        Route::get('/delete/{id}', 'GradeController@delete')->name('grade_delete')->middleware('permission:delete_grade');
        Route::get('/edit/{id}', 'GradeController@edit')->name('grade_edit')->middleware('permission:edit_grade');
        Route::post('/update/{id}', 'GradeController@update')->name('grade_update');
        Route::get('/list-grade/{id}', 'GradeController@listGradeOfSchool');
    });
    Route::group([
        'prefix' => 'map/category',
        'namespace' => 'Admins',
    ], function () {
        Route::get('', 'MapCategoryController@index')->name('map_category_index')->middleware('permission:view_category_map');
        Route::get('/create', 'MapCategoryController@create')->name('map_category_create')->middleware('permission:create_category_map');
        Route::post('/create', 'MapCategoryController@store');
        Route::get('/delete/{id}', 'MapCategoryController@delete')->name('map_category_delete')->middleware('permission:edit_category_map');
        Route::get('/edit/{id}', 'MapCategoryController@edit')->name('map_category_edit')->middleware('permission:delete_category_map');
        Route::post('/update/{id}', 'MapCategoryController@update')->name('map_category_update');
    });

    Route::group([
        'prefix' => 'news',
        'namespace' => 'Admins',
    ], function () {
        Route::get('','NewsController@index')->name('news_index')->middleware('permission:view_new');
        Route::get('/create','NewsController@create')->name('news_create')->middleware('permission:create_new');
        Route::post('/create','NewsController@store');
        Route::get('/delete/{id}','NewsController@delete')->name('news_delete')->middleware('permission:edit_new');
        Route::get('/edit/{id}','NewsController@edit')->name('news_edit')->middleware('permission:delete_new');
        Route::post('/update/{id}','NewsController@update')->name('news_update');
        Route::get('/update-status', 'NewsController@updateStatusAjax');
    });

    Route::group([
        'prefix' => 'news/category',
        'namespace' => 'Admins',
    ], function () {
        Route::get('', 'NewsCategoryController@index')->name('news_category_index')->middleware('permission:view_category_new');
        Route::get('/create', 'NewsCategoryController@create')->name('news_category_create')->middleware('permission:create_category_new');
        Route::post('/create', 'NewsCategoryController@store');
        Route::get('/delete/{id}', 'NewsCategoryController@delete')->name('news_category_delete')->middleware('permission:delete_category_new');
        Route::get('/edit/{id}', 'NewsCategoryController@edit')->name('news_category_edit')->middleware('permission:edit_category_new');
        Route::post('/update/{id}', 'NewsCategoryController@update')->name('news_category_update');
    });

    Route::group([
        'prefix' => 'supports',
        'namespace' => 'Admins',
    ], function () {

        Route::get('/', 'SupportsController@index')->name('supports.index');
        Route::get('/create', 'SupportsController@create')->name('supports.create');
        Route::post('/store', 'SupportsController@store')->name('supports.store');
        Route::get('/edit/{id}', 'SupportsController@edit')->name('supports.edit');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $table = 'questions';
    protected $fillable = [
        'course_id','type','subject','multiselect','point'
    ];
    public function course(){
        return $this->belongsTo(Course::class,'course_id','id');
     }
    public function getTypeQuestionAttribute()
    {
        $value = $this->type;
        if($value == 1){
            $typeQuestion = "Trắc nghiệm";
        }else{
            $typeQuestion = "Tự luận";
        }
        return $typeQuestion;
    }
    public function answer(){
        return $this->hasMany(Answer::class,'question_id','id');
    }
}

resources/views/admins/questions/add.blade.php
@extends('admin')
@section('content')
<div class="app-page-title app-page-title-custom">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-plus icon-gradient bg-happy-itmeo">
                </i>
            </div>
            <div>
                <h5>Thêm Mới Câu Hỏi</h5>
            </div>
        </div>
    </div>
</div>
<div class="main-card card main-card-custom">
    <div class="card-body">
        <form enctype="multipart/form-data" method="POST" novalidate="" action="{{route('question.question.store') }}" accept-charset="UTF-8" id="create_exhibition_form" name="create_exhibition_form" class="form-horizontal {{ $errors->any() ? 'was-validated' : '' }}">
            {{ csrf_field() }}

            @include ('admins.questions.form', [
                'question' => null,
                'courses' => $courses
                ])
                <div class="form-group">
                <div class="col-md-offset-2">
                <a href="{{ route('question.question.index',$id) }}" class="mb-2 mr-2 btn-icon btn-pill btn btn-outline-secondary"><i class="pe-7s-back btn-icon-wrapper"> </i>Quay lại</a>
                    <button type="submit" class="mb-2 mr-2 btn-icon btn-pill btn btn-outline-success"><i
                            class="mr-2 pe-7s-check btn-icon-wrapper"> </i>Lưu</button>
                    <button id="rediret-answer" class="mb-2 mr-2 btn-icon btn-pill btn btn-outline-success"><i
                            class="mr-2 pe-7s-check btn-icon-wrapper"> </i>Thêm câu trả lời</button>
                </div>

                </div>
        </form>

    </div>
</div>
@endsection

resources/views/admins/questions/edit.blade.php
@extends('admin')
@section('content')
<div class="app-page-title app-page-title-custom">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-plus icon-gradient bg-happy-itmeo">
                </i>
            </div>
            <div>
                <h5> Cập Nhập Câu Hỏi</h5>
            </div>
        </div>
    </div>
</div>
<div class="main-card card main-card-custom">
    <div class="card-body">
        <form enctype="multipart/form-data" method="POST" novalidate="" 
        action="{{route('question.question.update',$question->id) }}" accept-charset="UTF-8" id="create_exhibition_form" name="create_exhibition_form" class="form-horizontal {{ $errors->any() ? 'was-validated' : '' }}">
            {{ csrf_field() }}
            @include ('admins.questions.form', [
                'question' => $question,
                'courses' => $courses
                ])
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href="{{ route('question.question.index',$question->course_id) }}" class="mb-2 mr-2 btn-icon btn-pill btn btn-outline-secondary"><i class="pe-7s-back btn-icon-wrapper"> </i>Quay lại</a>
                    <button class="mb-2 mr-2 btn-icon btn-pill btn btn-outline-success"><i class="pe-7s-check btn-icon-wrapper"> </i>Cập nhập</button>
                </div>
            </div>

        </form>

    </div>
</div>
@endsection

resources/views/admins/questions/index.blade.php
@extends('admin')
@section('content')
<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-car icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>
                    Chi tiết khóa học
                </div>
            </div>

        </div>
    </div>
    @if(Session::has('message'))
    <div class="alert alert-success">
        <span class="glyphicon glyphicon-ok"></span>
        {!! session('message') !!}
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>

    </div>
    @endif
    <div class="col-md-12 pl-0">
        <div class="mb-3 card">
            <div class="p-0 card-body">
                <div class="dropdown-menu-header mt-0 mb-0">
                    <div class="dropdown-menu-header-inner bg-heavy-rain">
                        <div class="menu-header-image opacity-1"
                            style="background-image: url('assets/images/dropdown-header/city3.jpg');"></div>
                        <div class="menu-header-content text-dark p-2">
                            <h5 class="text-center menu-header-title">{{$course->name}}</h5>
                        </div>
                    </div>
                </div>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab-animated-1" role="tabpanel">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="ps">
                                    <div class="p-3">
                                        <div
                                            class="vertical-without-time vertical-timeline vertical-timeline--animate vertical-timeline--one-column">
                                            <div class="vertical-timeline-item vertical-timeline-element">
                                                <div>
                                                    <span class="vertical-timeline-element-icon bounce-in">
                                                        <i class="badge badge-dot badge-dot-xl badge-success"></i>
                                                    </span>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Danh mục khóa học</h6>
                                                        <p>{{$course->category->name}}
                                                        </p>
                                                    </div>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Ngày bắt dầu</h6>
                                                        <p>{{date("d-m-Y", strtotime($course->start_date))}}
                                                        </p>
                                                    </div>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Thời gian học</h6>
                                                        <p>{{$course->longtime}} Ngày
                                                        </p>
                                                    </div>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Người tạo</h6>
                                                        <p>{{$course->authorUser->name}}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="ps">
                                    <div class="p-3">
                                        <div
                                            class="vertical-without-time vertical-timeline vertical-timeline--animate vertical-timeline--one-column">
                                            <div class="vertical-timeline-item vertical-timeline-element">
                                                <div>
                                                    <span class="vertical-timeline-element-icon bounce-in">
                                                        <i class="badge badge-dot badge-dot-xl badge-success"></i>
                                                    </span>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Tỉ lệ điểm (trắc nghiêm/tự luận)</h6>
                                                        <p>{{$course->total_point_choice}} / {{100-$course->total_point_choice}}
                                                        </p>
                                                    </div>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Hiển thị</h6>
                                                        <p>@if($course->new)
                                                            Mới, 
                                                            @endif
                                                            @if($course->offer)
                                                            Đề xuất
                                                            @endif
                                                        </p>
                                                    </div>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Số câu hỏi</h6>
                                                        <p>{{$course->question->count()}}
                                                        </p>
                                                    </div>
                                                    <div class="vertical-timeline-element-content bounce-in">
                                                        <h6 class="timeline-title">Ngày tạo</h6>
                                                        <p>{{date("d-m-Y", strtotime($course->created_at))}}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="button p-2">
                        <a href="{{route('course.edit',$course->id)}}"
                            class="badge badge-success label-detail-answer">
                            <span class="mr-1">Cập nhập khóa học</span>
                        </a>


                <a href="{{ route('question.question.create',$id) }}" class="badge badge-success label-detail-answer"
                    href=""><i class="mr-1 pe-7s-plus btn-icon-wrapper">
                    </i>Thêm câu hỏi</a>
</div>
            </div>
        </div>
    </div>
    <div class="main-card card">
        <div class="panel-body panel-body-with-table">
            <div class="table-responsive">

                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên</th>
                            <th>Loại</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($questions as $question)
                        <tr>
                            <td>{!! Helper::indexPaginate($questions,$loop) !!}</td>
                            <td>{{$question->subject}}</td>
                            <td>{{$question->type_question}}</td>
                            <td>
                                @if($question->type == 1)
                                <a href="{{route('answer.answer.index',$question->id)}}"
                                    class="badge badge-success label-detail-answer">
                                    <span class="mr-1">Xem câu trả lời</span>
                                </a>
                                @endif
                            </td>
                            <td>
                                <form method="POST" action="{{route('question.question.destroy',$question->id)}}"
                                    accept-charset="UTF-8">
                                    <input name="_method" value="DELETE" type="hidden">
                                    {{ csrf_field() }}
                                    <div class=" w-100">
                                        <button type="submit"
                                            class="pull-right mb-2 mr-2 btn-icon btn-icon-only btn-shadow btn-dashed btn btn-outline-warning"
                                            title="Xóa" onclick="return confirm('Bạn muốn xóa ?')">
                                            <span class="pe-7s-trash" aria-hidden="true"></span>
                                        </button>
                                        <a href="{{route('question.question.edit',$question->id)}}"
                                            class="pull-right mb-2 mr-2 btn-icon btn-icon-only btn-shadow btn-dashed btn btn-outline-primary"
                                            title="Sửa">
                                            <span class="pe-7s-tools" aria-hidden="true"></span>
                                        </a>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>

        <div class="panel-footer">
            <div class="col-12">
                <div class="pagination pull-right">
                    {{ $questions->links()}}
                </div>
            </div>
        </div>

    </div>
</div>
@endsection